export const UPDATE_ANSWER_1 = 'UPDATE_ANSWER_1';
export const UPDATE_ANSWER_2 = 'UPDATE_ANSWER_2';
export const UPDATE_ANSWER_3 = 'UPDATE_ANSWER_3';
export const UPDATE_ANSWER_4 = 'UPDATE_ANSWER_4';
export const UPDATE_EMOTION = 'UPDATE_EMOTION';
export const CONCAT_THOUGHT = 'CONCAT_THOUGHT';
export const ADD_THOUGHT = 'ADD_THOUGHT';
